name = "MetidaNLopt"
uuid = "4e1362ca-e5a0-4237-9ffd-bca39e5440e3"
authors = ["Vladimir Arnautov <mail@pharmcat.net>"]
version = "0.5.0"

[deps]

Metida = "a1dec852-9fe5-11e9-361f-8d9fde67cfa2"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Metida = "0.14.3, 0.14.4"
NLopt = "0.6"
Reexport = "1"
julia = "1"

[extras]
Metida = "a1dec852-9fe5-11e9-361f-8d9fde67cfa2"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"

[targets]
test = ["Metida", "Test", "CSV", "DataFrames", "StatsBase", "StatsModels", "CategoricalArrays"]
